name: {{ cookiecutter.project_slug }}

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - snakemake-minimal=5.19.2
  - pip=20.1.1
  - pycryptodome=3.9.7
  - python=3.8.3

  - pip:
    - -e .
