# Specify file paths via function 'ospath' for cross-platform compatibility (Linux/Windows)
from os.path import join as ospath

# The following lines make the credentials cache available.
from {{ cookiecutter.project_slug }}.utils.credentials_cache import CredentialsCache
credentials_cache = CredentialsCache()

rule all:
    input:
{%- for item in cookiecutter.workflow_steps.replace(' ','').split(',') | reject('eq','...') %}
    {%- if loop.last %}
        ospath( 'data', '{{ item }}', '{run_id}_{{ item }}.out' )
    {%- endif %}
{%- endfor %}

{% for item in cookiecutter.workflow_steps.replace(' ','').split(',') | reject('eq','...') %}
rule {{ item }}:
    output: 
        ospath( 'data', '{{ item }}', '{run_id}_{{ item }}.out' )
    {%- if loop.previtem is defined %}
    input: 
        ospath( 'data', '{{ loop.previtem }}', '{run_id}_{{ loop.previtem }}.out' )
    {%- endif %}
    conda: 
        ospath( 'envs', '{{ item }}.yml' )
    script: 
        ospath( 'scripts', '{{ item }}.py' )
{% endfor %}
